### ISSUE TITLE
Some questions about the algorithm

### ISSUE THREAD

**Issue by rcywongaa** [asahin1/nbh-aug-planning#1]
Hi, first of all, thanks for the fascinating paper and for making the code available!

I have some questions that I would be very grateful if you could shed some light on.

1.  I was wondering if you've considered alternative proxies for the tangent vector, e.g. the normal of the wavefront? 
 This seems like a good choice for grid/lattice graphs where the density and position of the nodes are fixed.  It could also potentially improve runtime runtime since a secondary search to find the path neighborhood won't be necessary.

1.  I would expect the complexity to depend on the number of paths requested but that doesn't seem to be the case from the complexity bound of $O(k_n |V| \log(|V|))$.  Could you shed some light on that?  I would imagine if I asked for a very large number of paths, the algorithm would take much longer as it loops around an obstacle many times (each time producing a distinct path).

1.  Am I right to say that $1 < k_n < 2$?  Since the path neighborhood search is much smaller than the full search (assuming both using Dijkstra)

1.  If you don't mind, could you comment on the seemingly unexpectedly large runtime?  Vanilla Dijkstra's algorithm can usually find the shortest path for a graph with up to a million edges in less than a second.  However, in the paper, it seems even for a relatively modest graph with around a thousand edges, it still takes a few seconds to solve.
Is this just an effect of unoptimized research code (which is completely understandable!) or am I overlooking something that makes this comparison invalid (e.g. $k_n \gg 10$)?

Side note:  When running the algorithm, I only get a black screen on the GUI, even though the terminal show the algorithm running properly.  The GUI still receives key presses, but it's just a permanently black screen.  Any ideas?

Thank you for your time!

**Comment by asahin1** [comment]
Thanks for your interest in our work! I will address your questions below:

1. We have considered vector-based attributes to distinguish between vertices earlier. These include vectors that are tangent and normal to the wavefront. However, one of the main issues with using vectors was that they are usually at discrete angles depending on the grid configuration and depending on the shapes of the obstacles, the angle thresholds being used for distinguishing the vectors can be very sensitive. In other words, it could be difficult to tell whether the angle between the vectors is due to the grid resolution or an obstacle.
2. It is correct that the complexity depends on the number of paths requested. Requesting more paths means that more vertices will be expanded as the wavefront loops the obstacles. This will make $\mathcal{V}$ larger.
3. Essentially, any Dijkstra's search will have a complexity of $O(|\mathcal{V}|log(|\mathcal{V}|))$, so mentioning a factor of $k_n$ is not very helpful. In our case it was only to emphasize that the vertex expansion procedure in our case is more expensive than a regular Dijkstra's search by a factor of $k_n$. The complexity of vertex expansion itself depends on the path neighborhood radius, but it is safe to say that $k_n$ is much larger than 1.
4. As explained in 3, our vertex expansion procedure is expensive (requiring multiple path neighborhood sets to be generated and a comparison between those sets). I must admit that the code is also not well optimized.

The code has been developed in Ubuntu 20.04 and using OpenCV 3.4 on which the visualizations were running fine. I have experienced the black screen issues in Ubuntu 22.04 on a different hardware. I believe the graphics card play a role in the issue as well. I will have to investigate further and come back with a solution. In the meanwhile, feel free to share if you are using a different setup and I will look into that as well.

**Comment by rcywongaa** [comment]
Thanks a lot for the insights!

Would you mind sharing some intuition on the lower bound of the neighborhood radius $r_n$?
I understand that with $r_n$ too large, the algorithm will potentially miss out on branches so we would want $r_n$ as low as possible.  Considering a simplified case with no high cost regions and a uniformly discretized grid with diagonals (say with horizontal / vertical edges costing 1 and diagonal edges costing 1.414), is there ever a reason to have $r_n$ greater than 1.414?  i.e. if using the disk-shaped set ($\omega = 0$), the neighborhod would consist of those directly adjacent the vertex, bounded by the open set.
From Proposition 1, it seems that this would be sufficient?  Since for a uniformly expanding wavefront (Dijkstra), the separation of two paths from the same wavefront (i.e. non-distinct paths) cannot be larger than 1.414.

Thanks again for your time and insight!

**Comment by asahin1** [comment]
This is mainly because of the implementational detail **Rollback to grandparent** as named in the paper. Dependent upon the amount of rollback, neighborhood radii below a certain threshold would cause unnecessary branches. For now, we do not have any theoretical results on the relationship between the rollback radius $r_b$ and the neighborhood radius $r_n$, so it is not possible to come up with an exact lower bound.

**Comment by rcywongaa** [comment]
Hope you are doing well and thanks for the details so far!

I have some further questions regarding the cut point identification.  My understanding is that the cut points acts as a "virtual obstacle" that "pulls" two geometrically distinct paths apart so that they can be distinguished downstream.  Is that understanding correct?  If that's the case, we would potentially be creating many cut points between the high cost region and the goal (more if the size of the cut point radius is small)?

Would you mind also elaborating a bit figure 16(c) and (d)?  Is merge point synonemous with cut points?  If that's the case, why are the paths passing through the cut points?  Shouldn't they be obstacles that the path cannot go through?

Finally, do you have any experience applying your algorithm in 3D environment with non-prismatic obstacles, e.g. spherical obstacles?  My own experimentation seems to suggest it doesn't work since adjacent paths differ too little to be classified as distinct.  Just wondering if you had similar experiences or managed to overcome that somehow.

Thanks again for your time and help!

**Comment by asahin1** [comment]
Yes, that understanding about the cut points is correct. Our goal with identifying a set of cut points was to provide a remedy for the environments where the curvature is small, on which distinct neighborhoods cannot be identified for locally shortest paths. Whenever we run the algorithm with the cut point approach, our hope is to identify a connected set of cut points per corner (or bump) on the environment.

Yes, merge points are the same as cut points (there are some typos that we will correct). On 16c, the paths are actually not going through the cut points (I agree that it is not clear from the provided angle). However, contrary to what we expected, the cut points generate a disconnected set in this case. On 16d, one of the paths is clearly going through the cut points, which is deemed invalid (because it is not a locally shortest path). The reason why some paths may go through the cut points is because we allow a single layer of vertices at those coordinates instead of treating it entirely as an obstacle. We found this approach to work better with the specific implementations of the search algorithms we use (A* and S* algorithms from DOSL). See the below code segment where we identify two vertices at the same coordinates as the same if one of them is a cut point without performing the neighborhood comparison: https://github.com/asahin1/nbh-aug-planning/blob/24cf7b300bdf5d641ccdd5c20538c13a187d7667/include/myNode3D.cpp#L99-L103

We haven’t tried non-prismatic obstacles in 3D. But I would expect it to not behave well around a sphere as it can be classified into the low-curvature environment category that we described. Have you tried running the algorithm with cut points on it? I would expect that to be able to identify some distinct paths after some tuning of the parameters.

Sorry for the late response and thanks again for your interest in our work!
